export interface Navigation {
    profileImageClicked: boolean;
    profileImageHover: boolean;
    profilePrefClicked: boolean;
    profileSairClicked: boolean;
    profileBlockMouseOver:boolean;
    menuCadastroClicked: boolean;
    menuCadastroHover: boolean;
    viagemOSClicked: string;
    usuarioIDClicked:string;
    motoristaIDClicked:string;
    empresaIDClicked:string;
    searchTxt: string;
    searchStatus:string;
    searchUserTxt: string;
    searchUserStatus:string;
    searchMotTxt: string;
    searchEmpTxt: string;
    searchMotStatus:string;
    gerarRelatorioClicked: boolean;
    solicitarViagemClicked: boolean;
    novoUsuClicked: boolean;
    cadastrarMotClicked: boolean;
    cancelarViagemIDClicked:string;
    concluirViagemIDClicked:string;
    viagemOrderBy: string;
    atualizarListaViagens: boolean;
    atualizarListaMotoristas: boolean;
    atualizarListaEmpresas: boolean;
    atualizarListaUsuarios: boolean;
}